// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTeijX8VbAoJ1mWfFaVYKtJjTnQuElcrc',
    appId: '1:715004231361:web:431e2333946b8884695e40',
    messagingSenderId: '715004231361',
    projectId: 'parallel-universe-crysta-1f32b',
    authDomain: 'parallel-universe-crysta-1f32b.firebaseapp.com',
    storageBucket: 'parallel-universe-crysta-1f32b.firebasestorage.app',
    measurementId: 'G-KTYJ5C571X',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhe_bybrp-iDnM0-bttXH0UfJPplS5W1A',
    appId: '1:715004231361:ios:9fa7de84881ffb97695e40',
    messagingSenderId: '715004231361',
    projectId: 'parallel-universe-crysta-1f32b',
    storageBucket: 'parallel-universe-crysta-1f32b.firebasestorage.app',
    iosBundleId: 'com.example.parallelUniverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhe_bybrp-iDnM0-bttXH0UfJPplS5W1A',
    appId: '1:715004231361:ios:9fa7de84881ffb97695e40',
    messagingSenderId: '715004231361',
    projectId: 'parallel-universe-crysta-1f32b',
    storageBucket: 'parallel-universe-crysta-1f32b.firebasestorage.app',
    iosBundleId: 'com.example.parallelUniverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTeijX8VbAoJ1mWfFaVYKtJjTnQuElcrc',
    appId: '1:715004231361:web:6cc0a1661e6d501c695e40',
    messagingSenderId: '715004231361',
    projectId: 'parallel-universe-crysta-1f32b',
    authDomain: 'parallel-universe-crysta-1f32b.firebaseapp.com',
    storageBucket: 'parallel-universe-crysta-1f32b.firebasestorage.app',
    measurementId: 'G-VGB8LZ6T58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAII7EdXeXkMkeXCBap_ke2Aeh0wCP8Me8',
    appId: '1:715004231361:android:d6a5a1a6954dae49695e40',
    messagingSenderId: '715004231361',
    projectId: 'parallel-universe-crysta-1f32b',
    storageBucket: 'parallel-universe-crysta-1f32b.firebasestorage.app',
  );
}
